#!/bin/sh

#hotkey controller
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

#will need to change if monitor setup changes
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-I-1 -d I II III IV V


bspc config border_width         2
bspc config window_gap          12
#for kde panel
bspc config top_padding         32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#this features implementation inhibits interacting with the desktop
#bspc config focus_follows_pointer true

#dont know what this does yet
bspc rule -a Screenkey manage=off

# ignore plasma stuff and krunner
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off 
bspc rule -a yakuake layer=above state=floating


# custom rules for specific applications


