#!/bin/sh


sxhkd &

bspc monitor HDMI-0 -d dev web edu com mis
bspc monitor DVI-I-1 -d dev web edu com mis


bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding      28

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# ignore plasma stuff and krunner
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off 

#$HOME/.config/polybar/launch-polybar.sh


